import React, { createContext, useContext, useState, useEffect } from 'react';
import { getSettings } from '../services/settingsService';

type Language = 'en' | 'hi' | 'pa';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.alerts': 'Alerts',
    'nav.scan': 'Scan',
    'nav.snap': 'Snap (+50)',
    'nav.history': 'History',
    'nav.settings': 'Settings',
    'header.location': 'Your Location',
    'header.detect': 'Use Current Location',
    'header.detecting': 'Detecting...',
    'home.aqi': 'Air Quality Index',
    'home.updated': 'Updated',
    'home.pollutants': 'Pollutant Levels',
    'home.rank': 'Rank in Delhi',
    'home.trend': 'Trend (24h)',
    'home.cta': 'What Should I Do?',
    'home.impact.good': 'Air quality is considered satisfactory, and air pollution poses little or no risk.',
    'home.impact.satisfactory': 'Air quality is acceptable; however, for some pollutants there may be a moderate health concern.',
    'home.impact.moderate': 'Breathing discomfort for sensitive people. Avoid prolonged outdoor exertion.',
    'home.impact.poor': 'Breathing discomfort to most people on prolonged exposure. Wear a mask outdoors.',
    'home.impact.verypoor': 'Respiratory illness on prolonged exposure. Avoid all outdoor physical activities.',
    'home.impact.severe': 'Affects healthy people and seriously impacts those with existing diseases. Stay indoors.',
    'home.impact.good.short': 'Air is clean',
    'home.impact.satisfactory.short': 'Acceptable quality',
    'home.impact.moderate.short': 'Moderate concern',
    'home.impact.poor.short': 'Poor air quality',
    'home.impact.verypoor.short': 'Very Poor',
    'home.impact.severe.short': 'Severe Emergency',
    'settings.title': 'Settings',
    'settings.back': 'Back',
    'settings.save': 'Save',
    'settings.saved': 'Saved',
    'settings.section.location': 'Location',
    'settings.section.notifications': 'Notifications',
    'settings.section.privacy': 'Privacy & Data',
    'settings.section.display': 'Display',
    'settings.section.advanced': 'Advanced',
    'settings.section.about': 'About',
    'settings.lang': 'Language',
    
    // Action Recommendations
    'actions.title': 'ACTION PLAN',
    'actions.back': 'Back',
    'actions.basedOn': 'Based on Current AQI',
    'actions.immediate.title': 'DO THIS NOW',
    'actions.immediate.1': 'Stay indoors as much as possible',
    'actions.immediate.2': 'Close all windows and doors',
    'actions.immediate.3': 'Use air purifier if available',
    'actions.immediate.4': 'Wear N95 mask if going outside',
    'actions.immediate.5': 'Avoid outdoor exercise completely',
    'actions.special.title': 'SPECIAL PRECAUTIONS',
    'actions.special.children': 'For Children:',
    'actions.special.children.1': 'Keep indoors, no outdoor play',
    'actions.special.children.2': 'Watch for breathing difficulties',
    'actions.special.elderly': 'For Elderly & Pregnant:',
    'actions.special.elderly.1': 'Minimize all outdoor activity',
    'actions.special.elderly.2': 'Consult doctor if breathing issues',
    'actions.special.asthma': 'Asthma Patients:',
    'actions.special.asthma.1': 'Keep emergency inhaler ready',
    'actions.special.asthma.2': 'Avoid triggers (smoke, dust)',
    'actions.commute.title': 'COMMUTE TIPS',
    'actions.commute.1': 'Use cab/metro over two-wheeler',
    'actions.commute.2': 'Keep car AC on recirculation mode',
    'actions.commute.3': 'Avoid peak traffic hours',
    'actions.commute.4': 'Plan essential trips only',
    'actions.home.title': 'PROTECT YOUR HOME',
    'actions.home.1': 'Seal gaps in doors/windows',
    'actions.home.2': 'Use damp cloth to wipe surfaces',
    'actions.home.3': 'Add indoor plants',
    'actions.home.4': 'Avoid smoking or burning incense',
    'actions.gov.title': 'WHAT GOVERNMENT IS DOING',
    'actions.gov.1': 'Water sprinklers deployed',
    'actions.gov.2': 'Traffic control activated',
    'actions.gov.3': 'Construction ban being enforced',
    'actions.share': 'Share Tips',

    // Activity Planner
    'activity.title': 'Daily Activity Guide',
    'activity.walk.title': 'Outdoor Walk',
    'activity.walk.good': 'Go Ahead!',
    'activity.walk.moderate': 'Limit Time',
    'activity.walk.bad': 'Avoid',
    'activity.kids.title': 'Kids Playing',
    'activity.kids.good': 'Outdoors OK',
    'activity.kids.moderate': 'Light Play',
    'activity.kids.bad': 'Indoor Only',
    'activity.vent.title': 'Ventilation',
    'activity.vent.good': 'Open Windows',
    'activity.vent.moderate': 'Limit Opening',
    'activity.vent.bad': 'Keep Closed',
    'activity.travel.title': 'Travel',
    'activity.travel.good': 'Safe',
    'activity.travel.moderate': 'Wear Mask',
    'activity.travel.bad': 'Avoid',

    // Safe Commute
    'commute.title': 'Safe Commute Widget',
    'commute.home': 'Home',
    'commute.work': 'Office',
    'commute.route.fastest': 'Fastest Route',
    'commute.route.cleanest': 'Cleanest Route',
    'commute.cig.equiv': '≈ 2 cigarettes',
    'commute.green.zone': 'Through Green Zone',
    'commute.recommended': 'Recommended',
    'commute.min': 'min',

    // GreenLens
    'greenlens.detecting': 'Detecting Source...',
    'greenlens.detected': 'Biomass Burning Detected',
    'greenlens.confidence': '98% Confidence',
    'greenlens.submit': 'Submit Report',
    'greenlens.impact.verified': 'Impact Verified!',
    'greenlens.impact.msg': 'You saved ~200 people from toxic smoke.',
    'greenlens.reward.added': 'Green Credits added to Wallet',
    'greenlens.redeem': 'Redeem for Metro Pass',
    'greenlens.scan.another': 'Scan Another',
    'leaderboard.title': 'Top Ward Protectors',
    'leaderboard.rank': 'You are #4 in Rohini',
    'leaderboard.beat': 'Snap 2 more to beat Sharma_Ji',
  },
  hi: {
    'nav.home': 'होम',
    'nav.alerts': 'सूचनाएं',
    'nav.scan': 'स्कैन',
    'nav.snap': 'स्नैप (+50)',
    'nav.history': 'इतिहास',
    'nav.settings': 'सेटिंग्स',
    'header.location': 'आपका स्थान',
    'header.detect': 'वर्तमान स्थान का उपयोग करें',
    'header.detecting': 'खोज रहा है...',
    'home.aqi': 'वायु गुणवत्ता सूचकांक',
    'home.updated': 'अपडेट किया गया',
    'home.pollutants': 'प्रदूषक स्तर',
    'home.rank': 'दिल्ली में रैंक',
    'home.trend': 'रुझान (24 घंटे)',
    'home.cta': 'सुझाव देखें',
    'home.impact.good': 'वायु गुणवत्ता संतोषजनक मानी जाती है, और वायु प्रदूषण का कम या कोई जोखिम नहीं है।',
    'home.impact.satisfactory': 'वायु गुणवत्ता स्वीकार्य है; हालांकि, कुछ प्रदूषकों के लिए मध्यम स्वास्थ्य चिंता हो सकती है।',
    'home.impact.moderate': 'संवेदनशील लोगों के लिए सांस लेने में तकलीफ। लंबे समय तक बाहरी परिश्रम से बचें।',
    'home.impact.poor': 'लंबे समय तक संपर्क में रहने पर अधिकांश लोगों को सांस लेने में तकलीफ। बाहर मास्क पहनें।',
    'home.impact.verypoor': 'लंबे समय तक संपर्क में रहने पर श्वसन बीमारी। सभी बाहरी शारीरिक गतिविधियों से बचें।',
    'home.impact.severe': 'स्वस्थ लोगों को प्रभावित करता है और मौजूदा बीमारियों वाले लोगों को गंभीर रूप से प्रभावित करता है। घर के अंदर रहें।',
    'home.impact.good.short': 'हवा साफ है',
    'home.impact.satisfactory.short': 'स्वीकार्य गुणवत्ता',
    'home.impact.moderate.short': 'मध्यम चिंता',
    'home.impact.poor.short': 'खराब वायु गुणवत्ता',
    'home.impact.verypoor.short': 'बहुत खराब',
    'home.impact.severe.short': 'गंभीर आपातकाल',
    'settings.title': 'सेटिंग्स',
    'settings.back': 'पीछे',
    'settings.save': 'सहेजें',
    'settings.saved': 'सहेजा गया',
    'settings.section.location': 'स्थान',
    'settings.section.notifications': 'सूचनाएं',
    'settings.section.privacy': 'गोपनीयता और डेटा',
    'settings.section.display': 'प्रदर्शन',
    'settings.section.advanced': 'उन्नत',
    'settings.section.about': 'बारे में',
    'settings.lang': 'भाषा',

    'actions.title': 'कार्य योजना',
    'actions.back': 'पीछे',
    'actions.basedOn': 'वर्तमान AQI के आधार पर',
    'actions.immediate.title': 'अभी यह करें',
    'actions.immediate.1': 'जितना हो सके घर के अंदर रहें',
    'actions.immediate.2': 'सभी खिड़कियां और दरवाजे बंद रखें',
    'actions.immediate.3': 'यदि उपलब्ध हो तो एयर प्यूरीफायर का उपयोग करें',
    'actions.immediate.4': 'बाहर जाते समय N95 मास्क पहनें',
    'actions.immediate.5': 'बाहरी व्यायाम से पूरी तरह बचें',
    'actions.special.title': 'विशेष सावधानियां',
    'actions.special.children': 'बच्चों के लिए:',
    'actions.special.children.1': 'घर के अंदर रखें, बाहर न खेलें',
    'actions.special.children.2': 'सांस लेने में कठिनाई पर नज़र रखें',
    'actions.special.elderly': 'बुजुर्गों और गर्भवती के लिए:',
    'actions.special.elderly.1': 'बाहरी गतिविधियां कम करें',
    'actions.special.elderly.2': 'सांस की समस्या होने पर डॉक्टर से सलाह लें',
    'actions.special.asthma': 'अस्थमा के मरीज़:',
    'actions.special.asthma.1': 'आपातकालीन इनहेलर तैयार रखें',
    'actions.special.asthma.2': 'ट्रिगर्स (धुआं, धूल) से बचें',
    'actions.commute.title': 'यात्रा सुझाव',
    'actions.commute.1': 'दोपहिया वाहन की जगह कैब/मेट्रो का उपयोग करें',
    'actions.commute.2': 'कार का एसी रीसर्कुलेशन मोड पर रखें',
    'actions.commute.3': 'पीक ट्रैफिक (8-10 AM) से बचें',
    'actions.commute.4': 'केवल आवश्यक यात्राओं की योजना बनाएं',
    'actions.home.title': 'घर की सुरक्षा',
    'actions.home.1': 'दरवाजों/खिड़कियों में अंतराल बंद करें',
    'actions.home.2': 'सतहों को पोंछने के लिए गीले कपड़े का उपयोग करें',
    'actions.home.3': 'इंडोर पौधे (मनी प्लांट, स्नेक प्लांट) लगाएं',
    'actions.home.4': 'धूम्रपान या अगरबत्ती जलाने से बचें',
    'actions.gov.title': 'सरकार क्या कर रही है',
    'actions.gov.1': 'पानी के छिड़काव शुरू',
    'actions.gov.2': 'यातायात नियंत्रण सक्रिय',
    'actions.gov.3': 'निर्माण प्रतिबंध लागू',
    'actions.share': 'सुझाव साझा करें',

    // Activity Planner (Hindi)
    'activity.title': 'दैनिक गतिविधि गाइड',
    'activity.walk.title': 'बाहर टहलना',
    'activity.walk.good': 'जा सकते हैं!',
    'activity.walk.moderate': 'सीमित समय',
    'activity.walk.bad': 'परहेज करें',
    'activity.kids.title': 'बच्चों का खेलना',
    'activity.kids.good': 'बाहर सुरक्षित',
    'activity.kids.moderate': 'हल्का खेल',
    'activity.kids.bad': 'सिर्फ घर में',
    'activity.vent.title': 'वेंटिलेशन',
    'activity.vent.good': 'खिड़कियां खोलें',
    'activity.vent.moderate': 'कम खोलें',
    'activity.vent.bad': 'बंद रखें',
    'activity.travel.title': 'यात्रा',
    'activity.travel.good': 'सुरक्षित',
    'activity.travel.moderate': 'मास्क पहनें',
    'activity.travel.bad': 'टालें',

    // Safe Commute (Hindi)
    'commute.title': 'सुरक्षित यात्रा विजेट',
    'commute.home': 'घर',
    'commute.work': 'कार्यालय',
    'commute.route.fastest': 'सबसे तेज़ मार्ग',
    'commute.route.cleanest': 'सबसे साफ़ मार्ग',
    'commute.cig.equiv': '≈ 2 सिगरेट',
    'commute.green.zone': 'ग्रीन ज़ोन के माध्यम से',
    'commute.recommended': 'अनुशंसित',
    'commute.min': 'मिनट',

    // GreenLens (Hindi)
    'greenlens.detecting': 'स्रोत का पता लगाया जा रहा है...',
    'greenlens.detected': 'बायोमास जलने का पता चला',
    'greenlens.confidence': '98% विश्वास',
    'greenlens.submit': 'रिपोर्ट भेजें',
    'greenlens.impact.verified': 'प्रभाव सत्यापित!',
    'greenlens.impact.msg': 'आपने जहरीले धुएं से ~200 लोगों को बचाया।',
    'greenlens.reward.added': 'वॉलेट में ग्रीन क्रेडिट जोड़े गए',
    'greenlens.redeem': 'मेट्रो पास के लिए रिडीम करें',
    'greenlens.scan.another': 'दूसरा स्कैन करें',
    'leaderboard.title': 'वार्ड रक्षक',
    'leaderboard.rank': 'रोहिणी में आप #4 हैं',
    'leaderboard.beat': 'शर्मा जी को हराने के लिए 2 और स्नैप करें',
  },
  pa: {
    'nav.home': 'ਘਰ',
    'nav.alerts': 'ਅਲਰਟ',
    'nav.scan': 'ਸਕੈਨ',
    'nav.snap': 'ਸਨੈਪ (+50)',
    'nav.history': 'ਇਤਿਹਾਸ',
    'nav.settings': 'ਸੈਟਿੰਗਾਂ',
    'header.location': 'ਤੁਹਾਡਾ ਟਿਕਾਣਾ',
    'header.detect': 'ਮੌਜੂਦਾ ਟਿਕਾਣਾ ਵਰਤੋ',
    'header.detecting': 'ਖੋਜ ਰਿਹਾ ਹੈ...',
    'home.aqi': 'ਹਵਾ ਗੁਣਵੱਤਾ ਸੂਚਕਾਂਕ',
    'home.updated': 'ਅੱਪਡੇਟ ਕੀਤਾ',
    'home.pollutants': 'ਪ੍ਰਦੂਸ਼ਕ ਪੱਧਰ',
    'home.rank': 'ਦਿੱਲੀ ਵਿੱਚ ਰੈਂਕ',
    'home.trend': 'ਰੁਝਾਨ (24 ਘੰਟੇ)',
    'home.cta': 'ਸੁਝਾਅ ਦੇਖੋ',
    'home.impact.good': 'ਹਵਾ ਦੀ ਗੁਣਵੱਤਾ ਤਸੱਲੀਬਖਸ਼ ਮੰਨੀ ਜਾਂਦੀ ਹੈ, ਅਤੇ ਹਵਾ ਪ੍ਰਦੂਸ਼ਣ ਦਾ ਬਹੁਤ ਘੱਟ ਜਾਂ ਕੋਈ ਖਤਰਾ ਨਹੀਂ ਹੁੰਦਾ।',
    'home.impact.satisfactory': 'ਹਵਾ ਦੀ ਗੁਣਵੱਤਾ ਸਵੀਕਾਰਯੋਗ ਹੈ; ਹਾਲਾਂਕਿ, ਕੁਝ ਪ੍ਰਦੂਸ਼ਕਾਂ ਲਈ ਦਰਮਿਆਨੀ ਸਿਹਤ ਚਿੰਤਾ ਹੋ ਸਕਦੀ ਹੈ।',
    'home.impact.moderate': 'ਸੰਵੇਦਨਸ਼ੀਲ ਲੋਕਾਂ ਲਈ ਸਾਹ ਲੈਣ ਵਿੱਚ ਬੇਅਰਾਮੀ। ਲੰਬੇ ਸਮੇਂ ਤੱਕ ਬਾਹਰੀ ਮਿਹਨਤ ਤੋਂ ਬਚੋ।',
    'home.impact.poor': 'ਲੰਬੇ ਸਮੇਂ ਤੱਕ ਸੰਪਰਕ ਵਿੱਚ ਰਹਿਣ ਨਾਲ ਜ਼ਿਆਦਾਤਰ ਲੋਕਾਂ ਨੂੰ ਸਾਹ ਲੈਣ ਵਿੱਚ ਬੇਅਰਾਮੀ ਹੁੰਦੀ ਹੈ। ਬਾਹਰ ਮਾਸਕ ਪਹਿਨੋ।',
    'home.impact.verypoor': 'ਲੰਬੇ ਸਮੇਂ ਤੱਕ ਸੰਪਰਕ ਵਿੱਚ ਰਹਿਣ ਤੇ ਸਾਹ ਦੀ ਬਿਮਾਰੀ। ਸਾਰੀਆਂ ਬਾਹਰੀ ਸਰੀਰਕ ਗਤੀਵਿਧੀਆਂ ਤੋਂ ਬਚੋ।',
    'home.impact.severe': 'ਤੰਦਰੁਸਤ ਲੋਕਾਂ ਨੂੰ ਪ੍ਰਭਾਵਿਤ ਕਰਦਾ ਹੈ ਅਤੇ ਮੌਜੂਦਾ ਬਿਮਾਰੀਆਂ ਵਾਲੇ ਲੋਕਾਂ ਤੇ ਗੰਭੀਰ ਅਸਰ ਪਾਉਂਦਾ ਹੈ। ਘਰ ਦੇ ਅੰਦਰ ਰਹੋ।',
    'home.impact.good.short': 'ਹਵਾ ਸਾਫ਼ ਹੈ',
    'home.impact.satisfactory.short': 'ਸਵੀਕਾਰਯੋਗ ਗੁਣਵੱਤਾ',
    'home.impact.moderate.short': 'ਦਰਮਿਆਨੀ ਚਿੰਤਾ',
    'home.impact.poor.short': 'ਖਰਾਬ ਹਵਾ',
    'home.impact.verypoor.short': 'ਬਹੁਤ ਖਰਾਬ',
    'home.impact.severe.short': 'ਗੰਭੀਰ ਐਮਰਜੈਂਸੀ',
    'settings.title': 'ਸੈਟਿੰਗਾਂ',
    'settings.back': 'ਪਿੱਛੇ',
    'settings.save': 'ਸੇਵ ਕਰੋ',
    'settings.saved': 'ਸੁਰੱਖਿਅਤ ਕੀਤਾ',
    'settings.section.location': 'ਟਿਕਾਣਾ',
    'settings.section.notifications': 'ਸੂਚਨਾਵਾਂ',
    'settings.section.privacy': 'ਪਰਦੇਦਾਰੀ',
    'settings.section.display': 'ਡਿਸਪਲੇ',
    'settings.section.advanced': 'ਉੱਨਤ',
    'settings.section.about': 'ਬਾਰੇ',
    'settings.lang': 'ਭਾਸ਼ਾ',

    'actions.title': 'ਕਾਰਜ ਯੋਜਨਾ',
    'actions.back': 'ਪਿੱਛੇ',
    'actions.basedOn': 'ਮੌਜੂਦਾ AQI ਦੇ ਅਧਾਰ ਤੇ',
    'actions.immediate.title': 'ਹੁਣੇ ਕਰੋ',
    'actions.immediate.1': 'ਜਿੰਨਾ ਹੋ ਸਕੇ ਘਰ ਦੇ ਅੰਦਰ ਰਹੋ',
    'actions.immediate.2': 'ਸਾਰੀਆਂ ਖਿੜਕੀਆਂ ਅਤੇ ਦਰਵਾਜ਼ੇ ਬੰਦ ਰੱਖੋ',
    'actions.immediate.3': 'ਜੇ ਉਪਲਬਧ ਹੋਵੇ ਤਾਂ ਏਅਰ ਪਿਊਰੀਫਾਇਰ ਦੀ ਵਰਤੋਂ ਕਰੋ',
    'actions.immediate.4': 'ਬਾਹਰ ਜਾਣ ਵੇਲੇ N95 ਮਾਸਕ ਪਾਓ',
    'actions.immediate.5': 'ਬਾਹਰੀ ਕਸਰਤ ਤੋਂ ਪੂਰੀ ਤਰ੍ਹਾਂ ਬਚੋ',
    'actions.special.title': 'ਵਿਸ਼ੇਸ਼ ਸਾਵਧਾਨੀਆਂ',
    'actions.special.children': 'ਬੱਚਿਆਂ ਲਈ:',
    'actions.special.children.1': 'ਘਰ ਦੇ ਅੰਦਰ ਰੱਖੋ, ਬਾਹਰ ਨਾ ਖੇਡੋ',
    'actions.special.children.2': 'ਸਾਹ ਲੈਣ ਵਿੱਚ ਮੁਸ਼ਕਲਾਂ ਤੇ ਨਜ਼ਰ ਰੱਖੋ',
    'actions.special.elderly': 'ਬਜ਼ੁਰਗਾਂ ਅਤੇ ਗਰਭਵਤੀ ਲਈ:',
    'actions.special.elderly.1': 'ਬਾਹਰੀ ਗਤੀਵਿਧੀਆਂ ਘੱਟ ਕਰੋ',
    'actions.special.elderly.2': 'ਸਾਹ ਦੀ ਸਮੱਸਿਆ ਹੋਣ ਤੇ ਡਾਕਟਰ ਨਾਲ ਸੰਪਰਕ ਕਰੋ',
    'actions.special.asthma': 'ਦਮੇ ਦੇ ਮਰੀਜ਼:',
    'actions.special.asthma.1': 'ਐਮਰਜੈਂਸੀ ਇਨਹੇਲਰ ਤਿਆਰ ਰੱਖੋ',
    'actions.special.asthma.2': 'ਧੂੰਆਂ, ਧੂੜ ਤੋਂ ਬਚੋ',
    'actions.commute.title': 'ਯਾਤਰਾ ਸੁਝਾਅ',
    'actions.commute.1': 'ਦੋਪਹੀਆ ਵਾਹਨ ਦੀ ਥਾਂ ਕੈਬ/ਮੈਟਰੋ ਦੀ ਵਰਤੋਂ ਕਰੋ',
    'actions.commute.2': 'ਕਾਰ ਦਾ ਏਸੀ ਰੀਸਰਕੁਲੇਸ਼ਨ ਮੋਡ ਤੇ ਰੱਖੋ',
    'actions.commute.3': 'ਪੀਕ ਟ੍ਰੈਫਿਕ (8-10 AM) ਤੋਂ ਬਚੋ',
    'actions.commute.4': 'ਕੇਵਲ ਜ਼ਰੂਰੀ ਯਾਤਰਾਵਾਂ ਦੀ ਯੋਜਨਾ ਬਣਾਓ',
    'actions.home.title': 'ਘਰ ਦੀ ਸੁਰੱਖਿਆ',
    'actions.home.1': 'ਦਰਵਾਜ਼ਿਆਂ/ਖਿੜਕੀਆਂ ਵਿੱਚ ਖਾਲੀ ਥਾਂ ਬੰਦ ਕਰੋ',
    'actions.home.2': 'ਸਤਹਾਂ ਨੂੰ ਸਾਫ਼ ਕਰਨ ਲਈ ਗਿੱਲੇ ਕੱਪੜੇ ਦੀ ਵਰਤੋਂ ਕਰੋ',
    'actions.home.3': 'ਅੰਦਰੂਨੀ ਪੌਦੇ ਲਗਾਓ',
    'actions.home.4': 'ਸਿਗਰਟਨੋਸ਼ੀ ਜਾਂ ਧੂਫ਼ ਜਲਾਉਣ ਤੋਂ ਬਚੋ',
    'actions.gov.title': 'ਸਰਕਾਰ ਕੀ ਕਰ ਰਹੀ ਹੈ',
    'actions.gov.1': 'ਪਾਣੀ ਦੇ ਛਿੜਕਾਅ ਸ਼ੁਰੂ',
    'actions.gov.2': 'ਟ੍ਰੈਫਿਕ ਕੰਟਰੋਲ ਐਕਟਿਵ',
    'actions.gov.3': 'ਉਸਾਰੀ ਤੇ ਪਾਬੰਦੀ ਲਾਗੂ',
    'actions.share': 'ਸੁਝਾਅ ਸਾਂਝੇ ਕਰੋ',

    // Activity Planner (Punjabi)
    'activity.title': 'ਰੋਜ਼ਾਨਾ ਗਤੀਵਿਧੀ ਗਾਈਡ',
    'activity.walk.title': 'ਬਾਹਰ ਸੈਰ',
    'activity.walk.good': 'ਜਾ ਸਕਦੇ ਹੋ!',
    'activity.walk.moderate': 'ਸੀਮਤ ਸਮਾਂ',
    'activity.walk.bad': 'ਪਰਹੇਜ਼ ਕਰੋ',
    'activity.kids.title': 'ਬੱਚਿਆਂ ਦਾ ਖੇਡਣਾ',
    'activity.kids.good': 'ਬਾਹਰ ਸੁਰੱਖਿਅਤ',
    'activity.kids.moderate': 'ਹਲਕੀ ਖੇਡ',
    'activity.kids.bad': 'ਸਿਰਫ਼ ਘਰ ਵਿੱਚ',
    'activity.vent.title': 'ਵੈਂਟੀਲੇਸ਼ਨ',
    'activity.vent.good': 'ਖਿੜਕੀਆਂ ਖੋਲ੍ਹੋ',
    'activity.vent.moderate': 'ਘੱਟ ਖੋਲ੍ਹੋ',
    'activity.vent.bad': 'ਬੰਦ ਰੱਖੋ',
    'activity.travel.title': 'ਯਾਤਰਾ',
    'activity.travel.good': 'ਸੁਰੱਖਿਅਤ',
    'activity.travel.moderate': 'ਮਾਸਕ ਪਹਿਨੋ',
    'activity.travel.bad': 'ਟਾਲੋ',

    // Safe Commute (Punjabi)
    'commute.title': 'ਸੁਰੱਖਿਅਤ ਯਾਤਰਾ ਵਿਜੇਟ',
    'commute.home': 'ਘਰ',
    'commute.work': 'ਦਫ਼ਤਰ',
    'commute.route.fastest': 'ਸਭ ਤੋਂ ਤੇਜ਼ ਰੂਟ',
    'commute.route.cleanest': 'ਸਭ ਤੋਂ ਸਾਫ਼ ਰੂਟ',
    'commute.cig.equiv': '≈ 2 ਸਿਗਰਟਾਂ',
    'commute.green.zone': 'ਗ੍ਰੀਨ ਜ਼ੋਨ ਰਾਹੀਂ',
    'commute.recommended': 'ਸਿਫਾਰਸ਼ ਕੀਤੀ',
    'commute.min': 'ਮਿੰਟ',

    // GreenLens (Punjabi)
    'greenlens.detecting': 'ਸਰੋਤ ਲੱਭ ਰਿਹਾ ਹੈ...',
    'greenlens.detected': 'ਬਾਇਓਮਾਸ ਸਾੜਨ ਦਾ ਪਤਾ ਲੱਗਾ',
    'greenlens.confidence': '98% ਭਰੋਸਾ',
    'greenlens.submit': 'ਰਿਪੋਰਟ ਭੇਜੋ',
    'greenlens.impact.verified': 'ਪ੍ਰਭਾਵ ਦੀ ਪੁਸ਼ਟੀ ਹੋਈ!',
    'greenlens.impact.msg': 'ਤੁਸੀਂ ~200 ਲੋਕਾਂ ਨੂੰ ਜ਼ਹਿਰੀਲੇ ਧੂੰਏਂ ਤੋਂ ਬਚਾਇਆ।',
    'greenlens.reward.added': 'ਵਾਲਿਟ ਵਿੱਚ ਗ੍ਰੀਨ ਕ੍ਰੈਡਿਟ ਸ਼ਾਮਲ ਕੀਤੇ ਗਏ',
    'greenlens.redeem': 'ਮੈਟਰੋ ਪਾਸ ਲਈ ਰੀਡੀਮ ਕਰੋ',
    'greenlens.scan.another': 'ਇੱਕ ਹੋਰ ਸਕੈਨ ਕਰੋ',
    'leaderboard.title': 'ਵਾਰਡ ਪ੍ਰੋਟੈਕਟਰ',
    'leaderboard.rank': 'ਤੁਸੀਂ ਰੋਹਿਣੀ ਵਿੱਚ #4 ਹੋ',
    'leaderboard.beat': 'ਸ਼ਰਮਾ ਜੀ ਨੂੰ ਹਰਾਉਣ ਲਈ 2 ਹੋਰ ਸਨੈਪ ਕਰੋ',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    // Load initial language from secure settings
    const settings = getSettings();
    if (settings.language) {
      setLanguageState(settings.language);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    // Note: Settings persistence is handled by the Settings page calling settingsService
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};